import { Grid, useMediaQuery } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/layout/header";
import styles from "../styles/Home.module.css";

const AboutUs: NextPage = () => {
  const isMobile = useMediaQuery("(max-width: 1280px)");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <Grid container>
          <Grid
            item
            xs={6}
            padding={5}
            flexGrow={0}
            flexShrink={0}
            flexBasis={0.5}
            paddingRight={0}
            justifyContent={""}
          >
            <div className={[styles.italyFont, styles.aboutTitle].join(" ")}>
              About Our Company
            </div>
          </Grid>
          <Grid item xs={6} padding={5} paddingLeft={0}>
            <Image
              src="/about-img.png"
              alt="logo"
              layout="responsive"
              height={300}
              width={600}
            />
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default AboutUs;
