import { Grid, useMediaQuery } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Footer from "../components/layout/footer";
import Header from "../components/layout/header";
import ProductCard from "../components/products/productCard";
import styles from "../styles/Products.module.css";

const Products: NextPage = () => {
  const isMobile = useMediaQuery("(max-width: 1280px)");

  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>{"A&C - Products"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname === "/" ? <></> : <Header />}

      <main
        className={styles.main}
        style={{ padding: isMobile ? "0" : "1% 2%", paddingTop: "5%" }}
      >
        <Grid>
          <div className={[styles.italyFont, styles.productsTitle].join(" ")}>
            Our products
          </div>
          <div className={styles.productsTitleText}>
            Many desktop publishing packages and web pagend web page editors now
            use Lorem Ipsum as their test.
          </div>
          <ProductCard
            img="/products/addicto.png"
            title="Addicto"
            price={5.9}
          />
          <ProductCard img="/products/oreo.png" title="Oreo" price={5.9} />
          <ProductCard
            img="/about-img.png"
            title="yummy chocolate"
            price={5.9}
          />
          <ProductCard
            img="/products/nutella.png"
            title="Nutella"
            price={5.9}
          />
        </Grid>
      </main>

      {router.pathname === "/" ? <></> : <Footer />}
    </div>
  );
};

export default Products;
