import { Grid, useMediaQuery } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Carousel from "react-material-ui-carousel";
import Footer from "../components/layout/footer";
import Header from "../components/layout/header";
import styles from "../styles/Testimonial.module.css";

const Testimonial: NextPage = () => {
  const isMobile = useMediaQuery("(max-width: 1280px)");
  const router = useRouter();

  const testimonials = ["testimonial1", "testimonial2", "testimonial3"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Chocolat - Testimonial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname === "/" ? <></> : <Header />}

      <main className={styles.main}>
        <Grid container padding={5}>
          <Grid item xs={6} paddingTop={20}>
            <Image
              src="/about-img.png"
              alt="logo"
              layout="responsive"
              width={200}
              height={100}
            />
          </Grid>
          <Grid item xs={6} className={styles.carouselParentSection}>
            <div className={styles.sliderBg}></div>
            <div className={styles.sliderSection}>
              <div className={styles.carouselTitle}>Testimonial</div>
              <Carousel
                swipe={true}
                animation="slide"
                className={styles.carousel}
                navButtonsProps={{
                  style: {
                    backgroundColor: "#a04120",
                    opacity: 0.4,
                    width: 50,
                    height: 50,
                  },
                }}
              >
                {testimonials.map((testimonial, index) => (
                  <div key={index}>
                    <Grid minHeight={500} container>
                      <Grid item xs={5}>
                        <div className={styles.imgBox}>
                          <Image
                            src="/about-img.png"
                            alt="logo"
                            layout="fixed"
                            width={200}
                            height={100}
                          />
                        </div>
                      </Grid>
                      <Grid item xs={7} paddingTop={5}>
                        <div className={styles.testimonialTitle}>
                          Laura Ipsum
                        </div>
                        <div className={styles.testimonialText}>
                          long established fact that a reader will be distracted
                          by the readable content of a page when looking at its
                          layout. The point of using Lorem Ipsum is that it
                          haslong established fact that a reader will be
                          distracted by the readable content of a page when
                          looking at its layout. The point of using Lorem Ipsum
                          is that it haslong established fact that a reader will
                          be distracted by the readable content of a page when
                          looking at its layout. The point of using Lorem Ipsum
                          is that it has
                        </div>
                      </Grid>
                    </Grid>
                  </div>
                ))}
              </Carousel>
            </div>
          </Grid>
        </Grid>
      </main>

      {router.pathname === "/" ? <></> : <Footer />}
    </div>
  );
};

export default Testimonial;
