import { Grid, useMediaQuery } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Carousel from "react-material-ui-carousel";
import Footer from "../components/layout/footer";
import Header from "../components/layout/header";
import styles from "../styles/Testimonial.module.css";

const Testimonial: NextPage = () => {
  const isMobile = useMediaQuery("(max-width: 1280px)");

  const testimonials = ["testimonial1", "testimonial2", "testimonial3"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Chocolat - Testimonial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <Grid container padding={5}>
          <Grid item xs={6}>
            <Image
              src="/about-img.png"
              alt="logo"
              layout="responsive"
              width={200}
              height={100}
            />
          </Grid>
          <Grid item xs={6} className={styles.carouselParentSection}>
            <div className={styles.carouselSection}>
              <div className={styles.carouselTitle}>Testimonial</div>
              <Carousel
                swipe={true}
                animation="slide"
                className={styles.carousel}
              >
                {testimonials.map((testimonial, index) => (
                  <div>
                    <Grid minHeight={500}>
                      <div className={styles.imgBox}>
                        <Image
                          src="/about-img.png"
                          alt="logo"
                          layout="responsive"
                          width={200}
                          height={100}
                        />
                      </div>
                    </Grid>
                  </div>
                ))}
              </Carousel>
            </div>
          </Grid>
        </Grid>
      </main>

      <Footer />
    </div>
  );
};

export default Testimonial;
